#ifndef _CINEMATICMANAGER_H
#define _CINEMATICMANAGER_H

#include "Types.h"
#include "LargeObject.h"
#include "edC/edCBank.h"

#ifdef PLATFORM_PS2
#include <libvu0.h>
#endif

struct CinematicObjectB {
	int prtBuffer;
	uint flags_0x4;
	uint flags_0x8;
	int baseB;
	byte field_0x10;
	byte field_0x11;
	byte field_0x12;
	byte field_0x13;
	char* fileName;
	uint field_0x18;
	int field_0x1c;
	uint count_0x20;
	uint field_0x24;
	int field_0x28;
	int field_0x2c;
	float field_0x30;
	float field_0x34;
	float field_0x38;
	float field_0x3c;
	undefined4 field_0x40;
	int field_0x44;
	char* pBankName_0x48;
	int field_0x4c;
	char* pBankName_0x50;
	undefined4 field_0x54;
	float field_0x58;
	int field_0x5c;
	float field_0x60;
	int field_0x64;
	float field_0x68;
	int field_0x6c;
	int field_0x70;
	int field_0x74;
	undefined4 field_0x78;
	undefined4 field_0x7c;
	float field_0x80;
	int intOrPtrField;
	undefined field_0x88;
	undefined field_0x89;
	undefined field_0x8a;
	undefined field_0x8b;
	int intFieldC;
	int field_0x90;
	int field_0x94;
	int field_0x98;
	uint objCount_0x9c;
	int* field_0xa0;
	undefined field_0xa4;
	undefined field_0xa5;
	undefined field_0xa6;
	undefined field_0xa7;
	undefined field_0xa8;
	undefined field_0xa9;
	undefined field_0xaa;
	undefined field_0xab;
	undefined field_0xac;
	undefined field_0xad;
	undefined field_0xae;
	undefined field_0xaf;
	//struct CinematicObjectBLoadData cinematicLoadObject;
	undefined* field_0x100;
	undefined field_0x104;
	undefined field_0x105;
	undefined field_0x106;
	undefined field_0x107;
	undefined field_0x108;
	undefined field_0x109;
	undefined field_0x10a;
	undefined field_0x10b;
	undefined field_0x10c;
	undefined field_0x10d;
	undefined field_0x10e;
	undefined field_0x10f;
	undefined field_0x110;
	undefined field_0x111;
	undefined field_0x112;
	undefined field_0x113;
	undefined field_0x114;
	undefined field_0x115;
	undefined field_0x116;
	undefined field_0x117;
	undefined field_0x118;
	undefined field_0x119;
	undefined field_0x11a;
	undefined field_0x11b;
	undefined field_0x11c;
	undefined field_0x11d;
	undefined field_0x11e;
	undefined field_0x11f;
	sceVu0FMATRIX matrix_0x120;
	//struct CinematicFileData cinFileData;
	//struct TranslatedTextData textData;
	//struct MeshInfo* pMeshInfo;
	//struct MeshTransformParent* pMeshTransform;
	//struct ACutsceneActor** pCutsceneSubInfo;
	int numObjects_0x218;
	int* subObjBasePtr;
	undefined4 count_0x220;
	int count_0x224;
	//struct CineSunHolder* pCineSunHolderArray;
	int count_0x22c;
	//struct CineSpotHolder* pCineSpotHolderArray;
	int fileInfoStart;
	undefined4 field_0x238;
	struct Actor* pActor;
	float totalCutsceneDelta;
	uint* field_0x244;
	int* field_0x248;
	int* field_0x24c;
	int field_0x250;
	int* field_0x254;
	int field_0x258;
	int* field_0x25c;
	int intFieldE;
	undefined field_0x264;
	undefined field_0x265;
	undefined field_0x266;
	undefined field_0x267;
	undefined field_0x268;
	undefined field_0x269;
	undefined field_0x26a;
	undefined field_0x26b;
	undefined field_0x26c;
	undefined field_0x26d;
	undefined field_0x26e;
	undefined field_0x26f;
	undefined field_0x270;
	undefined field_0x271;
	undefined field_0x272;
	undefined field_0x273;
	int intFieldD;
	edCBank cineBank;
	int cineBankLoadStage_0x2b4;
	int soundCount_0x2b8;
	int sound_0x2bc;
	int playingSounds_0x2c0;
	undefined4 field_0x2c4;
	float field_0x2c8;
	float field_0x2cc;
	float field_0x2d0;
	float field_0x2d4;
	undefined field_0x2d8;
	undefined field_0x2d9;
	undefined field_0x2da;
	undefined field_0x2db;
	int particleSectionStart;
	int numberOfParticles;
	int buffer_0x2e4;
	int count_0x2e8;
	int field_0x2ec;
};

struct CinematicCameraView {
	//struct FrontendCameraView frontendCameraView;
	undefined4 field_0xb0;
	undefined4 field_0xb4;
	undefined4 field_0xb8;
	undefined field_0xbc;
	undefined field_0xbd;
	undefined field_0xbe;
	undefined field_0xbf;
};

class CinematicManager : public Manager {
public:
	CinematicManager::CinematicManager();

	struct CinematicObjectB** ppCinematicObjB_A;
	int numCutscenes_0x8;
	struct CinematicCameraView* pCameraLocationObj;
	struct CinematicObjectB** ppCinematicObjB_B;
	int count_0x14;
	struct CinematicObjectB* pCinematicObjB_0x18;
	struct CinematicObjectB* pSubObj_0x1c;
	int field_0x20;
	int field_0x24;
	undefined4 field_0x28;
	undefined4 field_0x2c;
	uint field_0x30;
	undefined4 field_0x34;
	undefined4 field_0x38;
	undefined field_0x3c;
	undefined field_0x3d;
	undefined field_0x3e;
	undefined field_0x3f;
	undefined4 field_0x40;
	undefined4 field_0x44;
	undefined field_0x48;
	undefined field_0x49;
	undefined field_0x4a;
	undefined field_0x4b;
	undefined field_0x4c;
	undefined field_0x4d;
	undefined field_0x4e;
	undefined field_0x4f;
	sceVu0FVECTOR vector_0x50;
	float x_0x60;
	float y_0x64;
	float z_0x68;
	undefined4 field_0x6c;
	sceVu0FMATRIX matrix_0x70;
	float field_0xb0;
	undefined field_0xb4;
	undefined field_0xb5;
	undefined field_0xb6;
	undefined field_0xb7;
	undefined field_0xb8;
	undefined field_0xb9;
	undefined field_0xba;
	undefined field_0xbb;
	undefined field_0xbc;
	undefined field_0xbd;
	undefined field_0xbe;
	undefined field_0xbf;
};

extern CinematicManager* g_CinematicManager_0048efc;

#endif // _CINEMATICMANAGER_H
